apiVersion: v1
kind: Service
metadata:
  name: auto-trade-program-byun618-2
spec:
  type: 'NodePort'
  selector:
    app: auto-trade-program-byun618-2
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
